version: '3.7'

services:
  db:
    image: mariadb                    # Tells Compose to use the 'mariadb' image for the 'db' service
    environment:
      MYSQL_ROOT_PASSWORD: apricots
      MYSQL_USER: MRDC              #This user getssuperuser privileges on MRDCdb
      MYSQL_PASSWORD: apricots      #password for MRDC user
      MYSQL_DATABASE: MRDCdb        # Tells Mariadb to initialize a database called 'MRDCdb' on first start
    volumes:
      - mariadbdata:/data/db        # Connects ./data-db in this repo to a named Docker volume
  web:
    build: ./django                 # Tells Compose to build the 'web' service from ./django (with Dockerfile)
    volumes:
      - ./django:/code              # Connects ./django in this repo to /code inside the web container
    ports:
      - "8000:8000"                 # Binds port 8000 to container port 8000 (format "HOST:CONTAINER")
    depends_on:
      - db                          # Tells Compose that 'db' needs to be started before 'web' can start
volumes:
    mariadbdata:
