version: '3.7'

services:
  db:
    image: mongo                    # Tells Compose to use the 'mongo' image for the 'db' service
    environment:
      MONGO_INITDB_DATABASE: djongo # Tells Mongo to initialize a database called 'djongo' on first start
    volumes:
      - mongodbdata:/data/db          # Connects ./data-db in this repo to /data/db inside the db container
  web:
    build: ./django                 # Tells Compose to build the 'web' service from ./django (with Dockerfile)
    volumes:
      - ./django:/code              # Connects ./django in this repo to /code inside the web container
    ports:
      - "8000:8000"                 # Binds port 8000 to container port 8000 (format "HOST:CONTAINER")
    depends_on:
      - db                          # Tells Compose that 'db' needs to be started before 'web' can start
volumes:
    mongodbdata: