version: '3.7'

services:
  db:
    image: mariadb                  # Tells Compose to use the 'mariadb' image for the 'db' service
    environment:
      MYSQL_DATABASE: 'django'      #name of the auto-created database
      MYSQL_USER: 'mrdc'            #This user getssuperuser privileges on the django database created above
      MYSQL_PASSWORD: 'apricots'    #password for MRDC user
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    volumes:
      - db:/var/lib/mysql           # Connects /var/lib/mysql in the container to a named Docker volume
  web:
    build: ./django                 # Tells Compose to build the 'web' service from ./django (with Dockerfile)
    volumes:
      - ./django:/code              # Connects ./django in this repo to /code inside the web container
      - static:/static
      - media:/media
    depends_on:
      - db                          # Tells Compose that 'db' needs to be started before 'web' can start
  redis:
    image: 'redis:latest'           # tells compose to use the official redis image
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - static:/data/static
      - media:/data/media
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    ports:
     - "8000:80"
volumes:
  db:
  static:
  media:
