version: '3'

services:
  db:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: djongo
    volumes:
      - ./data-db:/data/db
  web:
    build: ./django
    volumes:
      - ./django:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
